// Auth
export const CHECK_USER = "CHECK_USER";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const CHECK_USER_ERROR = "CHECK_USER_ERROR";
export const LOGIN_WITH_PASSWORD = "LOGIN_WITH_PASSWORD";
export const LOGIN_WITH_PASSWORD_SUCCESS = "LOGIN_WITH_PASSWORD_SUCCESS";
export const LOGIN_WITH_PASSWORD_ERROR = "LOGIN_WITH_PASSWORD_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const GET_STATE = "GET_STATE";
export const GET_STATE_SUCCESS = "GET_STATE_SUCCESS";
export const GET_STATE_ERROR = "GET_STATE_ERROR";
export const GET_CITY = "GET_CITY";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_ERROR = "GET_CITY_ERROR";
export const SET_CITY = "SET_CITY";
export const ENQUIRY = "ENQUIRY";
export const ENQUIRY_SUCCESS = "ENQUIRY_SUCCESS";
export const ENQUIRY_ERROR = "ENQUIRY_ERROR";
export const SERVICE_ENQUIRY = "SERVICE_ENQUIRY";
export const SERVICE_ENQUIRY_SUCCESS = "SERVICE_ENQUIRY_SUCCESS";
export const SERVICE_ENQUIRY_ERROR = "SERVICE_ENQUIRY_ERROR";
export const SERVICE_INFORMATION = "SERVICE_INFORMATION";
export const SERVICE_INFORMATION_SUCCESS = "SERVICE_INFORMATION_SUCCESS";
export const SERVICE_INFORMATION_ERROR = "SERVICE_INFORMATION_ERROR";

// Splash
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS";

// Classified
export const FETCH_EMERGENCY = "FETCH_EMERGENCY";
export const FETCH_EMERGENCY_SUCCESS = "FETCH_EMERGENCY_SUCCESS";
export const FETCH_EMERGENCY_ERROR = "FETCH_EMERGENCY_ERROR";
export const SEARCH_SERVICE = "SEARCH_SERVICE";
export const SEARCH_SERVICE_SUCCESS = "SEARCH_SERVICE_SUCCESS";
export const SEARCH_SERVICE_ERROR = "SEARCH_SERVICE_ERROR";

export * from './auth/actions';
export * from './classified/actions';